# Generated by Django 2.2.3 on 2019-11-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppartmentModel',
            fields=[
                ('Appartmentno', models.IntegerField(primary_key=True, serialize=False)),
                ('road_no', models.IntegerField()),
                ('survey_no', models.IntegerField()),
                ('cost_perbhk', models.IntegerField()),
                ('otherexpense', models.IntegerField()),
                ('BHK', models.CharField(max_length=20)),
                ('facing', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('Appartment_image', models.ImageField(upload_to='appartment_image/')),
                ('totalcost', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=30)),
                ('DOJ', models.DateField()),
                ('designsation', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=40)),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PlotModel',
            fields=[
                ('plotno', models.IntegerField(primary_key=True, serialize=False)),
                ('road_no', models.IntegerField()),
                ('survey_no', models.IntegerField()),
                ('cost_persqryrd', models.IntegerField()),
                ('otherexpense', models.IntegerField()),
                ('boundry', models.DecimalField(decimal_places=2, max_digits=5)),
                ('facing', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('property_image', models.ImageField(upload_to='property_image/')),
                ('total_cost', models.IntegerField(default=False)),
            ],
        ),
    ]
